package com.db.lucasLima.testProjectAdmission.Model;

public class xml {
	
	public String getXml() {
		return xml;
	}
	
	private String xml = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n"
			+ "<DOC xmlns=\"http://www.bcb.gov.br/SPB/SLC0001.xsd\">\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "   <BCMSG>\r\n"
			+ "      <IdentdEmissor>99999999</IdentdEmissor>\r\n"
			+ "      <IdentdDestinatario>12345678</IdentdDestinatario>\r\n"
			+ "      <Grupo_Seq>\r\n"
			+ "         <NumSeq>1</NumSeq>\r\n"
			+ "         <IndrCont>N</IndrCont>\r\n"
			+ "      </Grupo_Seq>\r\n"
			+ "      <DomSist>SPB01</DomSist>\r\n"
			+ "      <NUOp>12345678912345678912345</NUOp>\r\n"
			+ "   </BCMSG>\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "\r\n"
			+ "   <SISMSG>\r\n"
			+ "      <SLC0001>\r\n"
			+ "         <CodMsg>SLC0001</CodMsg>\r\n"
			+ "         <NumCtrlSLC>12345678912345678912</NumCtrlSLC>\r\n"
			+ "         <ISPBIF>12345678</ISPBIF>\r\n"
			+ "         <TpInf>P</TpInf>\r\n"
			+ "         <Grupo_SLC0001_Liquid>\r\n"
			+ "            <DtLiquid>2022-01-01</DtLiquid>\r\n"
			+ "            <NumSeqCicloLiquid>1</NumSeqCicloLiquid>\r\n"
			+ "            <Grupo_SLC0001_Prodt>\r\n"
			+ "               <CodProdt>ACC</CodProdt>\r\n"
			+ "               <Grupo_SLC0001_LiquidProdt>\r\n"
			+ "                  <IdentdLinhaBilat>12345678ACC3456789</IdentdLinhaBilat>\r\n"
			+ "                  <TpDeb_Cred>D</TpDeb_Cred>\r\n"
			+ "                  <ISPBIFCredtd>99999999</ISPBIFCredtd>\r\n"
			+ "                  <ISPBIFDebtd>99999999</ISPBIFDebtd>\r\n"
			+ "                  <VlrLanc>4000.00</VlrLanc>\r\n"
			+ "                  <CNPJNLiqdantDebtd>99929009000149</CNPJNLiqdantDebtd>\r\n"
			+ "                  <NomCliDebtd>JET</NomCliDebtd>\r\n"
			+ "                  <CNPJNLiqdantCredtd>17061147000194</CNPJNLiqdantCredtd>\r\n"
			+ "                  <NomCliCredtd>BANCO</NomCliCredtd>\r\n"
			+ "                  <TpTranscSLC>02</TpTranscSLC>\r\n"
			+ "               </Grupo_SLC0001_LiquidProdt>\r\n"
			+ "            </Grupo_SLC0001_Prodt>\r\n"
			+ "            <Grupo_SLC0001_Prodt>\r\n"
			+ "               <CodProdt>VCC</CodProdt>\r\n"
			+ "               <Grupo_SLC0001_LiquidProdt>\r\n"
			+ "                  <IdentdLinhaBilat>12345678VCC3456789</IdentdLinhaBilat>\r\n"
			+ "                  <TpDeb_Cred>C</TpDeb_Cred>\r\n"
			+ "                  <ISPBIFCredtd>99999999</ISPBIFCredtd>\r\n"
			+ "                  <ISPBIFDebtd>99999999</ISPBIFDebtd>\r\n"
			+ "                  <VlrLanc>16990.85</VlrLanc>\r\n"
			+ "                  <CNPJNLiqdantDebtd>47515515000198</CNPJNLiqdantDebtd>\r\n"
			+ "                  <NomCliDebtd>BANCOBOB</NomCliDebtd>\r\n"
			+ "                  <CNPJNLiqdantCredtd>02181332000145</CNPJNLiqdantCredtd>\r\n"
			+ "                  <NomCliCredtd>BANCO</NomCliCredtd>\r\n"
			+ "                  <TpTranscSLC>02</TpTranscSLC>\r\n"
			+ "               </Grupo_SLC0001_LiquidProdt>\r\n"
			+ "               <Grupo_SLC0001_LiquidProdt>\r\n"
			+ "                  <IdentdLinhaBilat>10045678VCC3456789</IdentdLinhaBilat>\r\n"
			+ "                  <TpDeb_Cred>C</TpDeb_Cred>\r\n"
			+ "                  <ISPBIFCredtd>99999999</ISPBIFCredtd>\r\n"
			+ "                  <ISPBIFDebtd>99999999</ISPBIFDebtd>\r\n"
			+ "                  <VlrLanc>3171.76</VlrLanc>\r\n"
			+ "                  <CNPJNLiqdantDebtd>50276286000100</CNPJNLiqdantDebtd>\r\n"
			+ "                  <NomCliDebtd>TRIANGULO</NomCliDebtd>\r\n"
			+ "                  <CNPJNLiqdantCredtd>23333472000161</CNPJNLiqdantCredtd>\r\n"
			+ "                  <NomCliCredtd>BANCO</NomCliCredtd>\r\n"
			+ "                  <TpTranscSLC>02</TpTranscSLC>\r\n"
			+ "               </Grupo_SLC0001_LiquidProdt>\r\n"
			+ "            </Grupo_SLC0001_Prodt>\r\n"
			+ "            <Grupo_SLC0001_Prodt>\r\n"
			+ "               <CodProdt>MCC</CodProdt>\r\n"
			+ "               <Grupo_SLC0001_LiquidProdt>\r\n"
			+ "                  <IdentdLinhaBilat>12345678MCC1633000</IdentdLinhaBilat>\r\n"
			+ "                  <TpDeb_Cred>C</TpDeb_Cred>\r\n"
			+ "                  <ISPBIFCredtd>99999999</ISPBIFCredtd>\r\n"
			+ "                  <ISPBIFDebtd>99999999</ISPBIFDebtd>\r\n"
			+ "                  <VlrLanc>5462.12</VlrLanc>\r\n"
			+ "                  <CNPJNLiqdantDebtd>93052785000127</CNPJNLiqdantDebtd>\r\n"
			+ "                  <NomCliDebtd>TRIANGULOBOB</NomCliDebtd>\r\n"
			+ "                  <CNPJNLiqdantCredtd>07284171000139</CNPJNLiqdantCredtd>\r\n"
			+ "                  <NomCliCredtd>BANCO</NomCliCredtd>\r\n"
			+ "                  <TpTranscSLC>02</TpTranscSLC>\r\n"
			+ "               </Grupo_SLC0001_LiquidProdt>\r\n"
			+ "            </Grupo_SLC0001_Prodt>\r\n"
			+ "            <Grupo_SLC0001_Prodt>\r\n"
			+ "               <CodProdt>CBC</CodProdt>\r\n"
			+ "               <Grupo_SLC0001_LiquidProdt>\r\n"
			+ "                  <IdentdLinhaBilat>12345678CBC1633012</IdentdLinhaBilat>\r\n"
			+ "                  <TpDeb_Cred>C</TpDeb_Cred>\r\n"
			+ "                  <ISPBIFCredtd>99999999</ISPBIFCredtd>\r\n"
			+ "                  <ISPBIFDebtd>99999999</ISPBIFDebtd>\r\n"
			+ "                  <VlrLanc>21446.69</VlrLanc>\r\n"
			+ "                  <CNPJNLiqdantDebtd>74816392000106</CNPJNLiqdantDebtd>\r\n"
			+ "                  <NomCliDebtd>BANCOBOB</NomCliDebtd>\r\n"
			+ "                  <CNPJNLiqdantCredtd>30101382000100</CNPJNLiqdantCredtd>\r\n"
			+ "                  <NomCliCredtd>TRIANGULOBANCO</NomCliCredtd>\r\n"
			+ "                  <TpTranscSLC>02</TpTranscSLC>\r\n"
			+ "               </Grupo_SLC0001_LiquidProdt>\r\n"
			+ "            </Grupo_SLC0001_Prodt>\r\n"
			+ "         </Grupo_SLC0001_Liquid>\r\n"
			+ "      \r\n"
			+ "         <DtHrSLC>2022-01-01T08:40:21</DtHrSLC>\r\n"
			+ "         <DtMovto>2022-01-01</DtMovto>\r\n"
			+ "      </SLC0001>\r\n"
			+ "   </SISMSG>\r\n"
			+ "</DOC>";
	
	
}